name: hemmah_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: CascadiaMono
      fonts:
        - asset: assets/fonts/CascadiaMono-Regular.ttf
        - asset: assets/fonts/CascadiaMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/CascadiaMono-SemiBold.ttf
          weight: 600